import assert from 'node:assert/strict';
import {candidates,createRound,answer,advance,score} from '../dist/quiz-engine.mjs';
import {readData} from './read-data.mjs';
const layers=readData('display-boundaries.json').subdivisions.features.map(feature=>({feature}));
layers.push({feature:{properties:{adcode:659013,provinceCode:650000,level:'city'},geometry:null}});
const mainland=candidates(layers,{includeTaiwan:false}),country=candidates(layers),taiwan=candidates(layers,{scope:710000,includeTaiwan:false});
assert.equal(mainland.length,333);assert.equal(country.length,355);assert.equal(taiwan.length,22);
assert(mainland.every(l=>l.feature.properties.level==='city'&&String(l.feature.properties.adcode).slice(2,4)!=='90'));
for(const code of [110000,120000,310000,500000,810000,820000])assert.equal(candidates(layers,{scope:code}).length,0,'Municipal districts must not become prefectures');
const hubei=candidates(layers,{scope:'420000'});assert.equal(hubei.length,13);
const xinjiang=candidates(layers,{scope:'650000'});assert.equal(xinjiang.length,14);
assert(xinjiang.every(l=>!String(l.feature.properties.adcode).startsWith('6590')));
const round=createRound(hubei,20,()=>.4);assert.equal(round.questions.length,13);
assert.equal(new Set(round.questions.map(l=>l.feature.properties.adcode)).size,13,'Question repeats');
assert.equal(advance(round),false,'Advance requires an answer');
assert.equal(answer(round,110000),null,'Out-of-scope answer was accepted');
assert.equal(round.results.length,0);
const first=round.questions[0].feature.properties.adcode;
assert.equal(answer(round,first).status,'correct');assert.equal(answer(round,first),null,'Repeated click was scored twice');
assert.equal(advance(round),true);
assert.equal(answer(round,first).status,'incorrect');advance(round);
assert.equal(answer(round).status,'skipped');advance(round);
while(!round.complete){answer(round,round.questions[round.index].feature.properties.adcode);advance(round);}
assert.deepEqual(score(round),{correct:11,incorrect:1,skipped:1,total:13,answered:13});
assert.equal(answer(round,first),null);assert.equal(advance(round),false);
assert.equal(createRound(country,'all').questions.length,355);assert.equal(createRound(hubei,10).questions.length,10);
assert.throws(()=>createRound([]));
assert.deepEqual(createRound(hubei,10).results,[],'New round retained old results');
console.log(JSON.stringify({mainlandPlaces:333,withTaiwan:355,taiwanDivisions:22,hubeiPlaces:13,xinjiangPrefectures:14,uniqueQuestions:true,scoringAndScopeVerified:true}));
