import fs from 'node:fs';
import assert from 'node:assert/strict';
import {spawnSync} from 'node:child_process';
import {gunzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';
import mapshaper from 'mapshaper';
import {readData} from './read-data.mjs';
import {transformGeometry} from './coordinates.mjs';
import {correctJiamusi} from './jiamusi-correction.mjs';

const show=file=>{const r=spawnSync('git',['-c','safe.directory='+process.cwd().replaceAll('\\','/'),'show','caf695223030aff2bc1d187c8724567431649b3b:dist/data/'+file],{maxBuffer:50e6});assert.equal(r.status,0);return r.stdout;};
const manifest=JSON.parse(show('display-boundaries.parts.json'));
const before=JSON.parse(gunzipSync(Buffer.concat(manifest.parts.map(show))));
const after=readData('display-boundaries.json');
const polygons=g=>g.type==='Polygon'?[g.coordinates]:g.coordinates;
const inRing=([x,y],r)=>{let inside=false;for(let i=0,j=r.length-1;i<r.length;j=i++){const a=r[i],b=r[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;};
const contains=(g,p)=>polygons(g).some(r=>inRing(p,r[0])&&!r.slice(1).some(h=>inRing(p,h)));
const area=g=>polygons(g).reduce((s,p)=>s+p.reduce((a,r,i)=>a+(i?-1:1)*Math.abs(r.slice(1).reduce((t,b,j)=>t+(r[j][0]-r[0][0])*(b[1]-r[0][1])-(b[0]-r[0][0])*(r[j][1]-r[0][1]),0)/2),0),0);
const city=(data,code)=>data.subdivisions.features.find(f=>f.properties.adcode===code);
// Guangdong's later Shenzhen physical coast update is checked separately.
for(const f of before.provinces.features)if(f.properties.adcode!==440000)assert.deepEqual(after.provinces.features.find(c=>c.properties.adcode===f.properties.adcode),f,'Unrelated provincial coverage stays exact');
let unchanged=0;
for(const f of before.subdivisions.features){const now=city(after,f.properties.adcode);assert.deepEqual(now.properties,f.properties);if(![230800,230900,440300].includes(f.properties.adcode)){assert.deepEqual(now.geometry,f.geometry);unchanged++;}}
assert.equal(unchanged,499);
assert.deepEqual(correctJiamusi(after.subdivisions.features),after.subdivisions.features,'Correction is idempotent');
assert.equal(polygons(city(after,230800).geometry).length,1,'Jiamusi has no detached part here');
assert.equal(polygons(city(after,230900).geometry).length,1,'The part joins Qitaihe');
const previousArea=[230800,230900].reduce((s,c)=>s+area(city(before,c).geometry),0);
const currentArea=[230800,230900].reduce((s,c)=>s+area(city(after,c).geometry),0);
assert(Math.abs(previousArea-currentArea)<1e-12,'No land is lost or added');
const original=readData('230000.json').features.find(f=>f.properties.adcode===230800).geometry.coordinates[1];
const part=transformGeometry({type:'Polygon',coordinates:original});
const point=part.coordinates[0].slice(0,-1).reduce((p,c)=>[p[0]+c[0]/20,p[1]+c[1]/20],[0,0]);
assert(contains(part,point));
assert(contains(city(before,230800).geometry,point),'Point reproduces the old error');
assert.deepEqual(after.subdivisions.features.filter(f=>contains(f.geometry,point)).map(f=>f.properties.adcode),[230900],'Click now resolves to Qitaihe');
const record=readData('boundary-corrections.json').corrections[0],reference=readData('qiezihe-reference.json');
assert.equal(createHash('sha256').update(fs.readFileSync('scripts/additional-sources/qiezihe-areacity-record.csv')).digest('hex'),record.reference.sourceRecordSHA256);
assert.equal(createHash('sha256').update(fs.readFileSync('dist/data/qiezihe-reference.json.gz')).digest('hex'),record.reference.sha256);
assert.equal(reference.features[0].properties.adcode,230904);
assert(contains(reference.features[0].geometry,point));
const clipped=JSON.parse((await mapshaper.applyCommands('-i part.json -clip reference.json -o out.json format=geojson geojson-type=FeatureCollection',{'part.json':{type:'FeatureCollection',features:[{type:'Feature',properties:{id:1},geometry:part}]},'reference.json':reference}))['out.json']);
const overlap=clipped.features.reduce((s,f)=>s+area(f.geometry),0)/area(part);
assert(overlap>0.98,'Recheck ownership if the reference changes');
assert(Math.abs(overlap-record.reference.originalPartCoverageFraction)<1e-5);
for(const file of ['korea-boundaries.bin','korea-outline.bin'])assert.deepEqual(fs.readFileSync('dist/data/'+file),show(file),'Korean data remains exact');
console.log({unchangedSubdivisions:unchanged,referenceCoveragePercent:overlap*100,selection:230900,unrelatedProvincialAndKoreanGeometryUnchanged:true});
