import assert from 'node:assert/strict';
import {candidates,createRound,answer,advance,score} from '../dist/quiz-engine.mjs';
import {readData} from './read-data.mjs';
const layers=readData('display-boundaries.json').subdivisions.features.map(feature=>({feature}));
layers.push({feature:{properties:{adcode:659013,provinceCode:650000,level:'city'},geometry:null}});
const mainland=candidates(layers,{includeTaiwan:false}),country=candidates(layers),taiwan=candidates(layers,{scope:710000,includeTaiwan:false});
assert.equal(mainland.length,333);assert.equal(country.length,355);assert.equal(taiwan.length,22);
assert(mainland.every(l=>l.feature.properties.level==='city'&&String(l.feature.properties.adcode).slice(2,4)!=='90'));
for(const code of [110000,120000,310000,500000,810000,820000])assert.equal(candidates(layers,{scope:code}).length,0,'Municipal districts must not become prefectures');
const hubei=candidates(layers,{scope:'420000'});assert.equal(hubei.length,13);
const xinjiang=candidates(layers,{scope:'650000'});assert.equal(xinjiang.length,14);
assert(xinjiang.every(l=>!String(l.feature.properties.adcode).startsWith('6590')));
const round=createRound(hubei,20,()=>.4);assert.equal(round.questions.length,13);
assert.equal(new Set(round.questions.map(l=>l.feature.properties.adcode)).size,13,'Question repeats');
assert.equal(advance(round),false,'Advance requires an answer');
assert.equal(answer(round,110000),null,'Out-of-scope answer was accepted');
assert.equal(round.results.length,0);
const first=round.questions[0].feature.properties.adcode;
assert.equal(answer(round,first).status,'correct');assert.equal(answer(round,first),null,'Repeated click was scored twice');
assert.equal(advance(round),true);
assert.equal(answer(round,first).status,'incorrect');advance(round);
assert.equal(answer(round).status,'skipped');advance(round);
while(!round.complete){answer(round,round.questions[round.index].feature.properties.adcode);advance(round);}
assert.deepEqual(score(round),{correct:11,incorrect:1,skipped:1,total:13,answered:13});
assert.equal(answer(round,first),null);assert.equal(advance(round),false);
assert.equal(createRound(country,'all').questions.length,355);assert.equal(createRound(hubei,10).questions.length,10);
assert.throws(()=>createRound([]));
assert.deepEqual(createRound(hubei,10).results,[],'New round retained old results');
console.log(JSON.stringify({mainlandPlaces:333,withTaiwan:355,taiwanDivisions:22,hubeiPlaces:13,xinjiangPrefectures:14,uniqueQuestions:true,scoringAndScopeVerified:true}));

// Exercise the map controller across correct, incorrect, revealed and completed questions.
const {readFileSync}=await import('node:fs'),{runInNewContext}=await import('node:vm');
const app=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');
const extract=(start,end)=>app.slice(app.indexOf(start),app.indexOf(end,app.indexOf(start)));
const mapRound=createRound(hubei,4,()=>.4),states=new Map(),highlighted=[];
const quiz={active:true,round:mapRound,highlighted,reviewLayer:null};
let completed=false;
const context={quiz,cameraBusy:false,AtlasQuiz:{advance},Set,clearHover(){},updateLabels(){},setRegionState(layer,state){states.set(layer.feature.properties.adcode,state);},renderQuizQuestion(){},fitQuizScope(){},renderQuizResults(){completed=true;}};
runInNewContext(extract('function clearQuizHighlights(', 'function syncQuizStyle(')+extract('async function nextQuizQuestion(', 'function viewQuizAnswer('),context);
const mark=(layer,correct=true)=>{quiz.highlighted.push(layer);states.set(layer.feature.properties.adcode,{quizCorrect:correct,quizWrong:!correct});};
const a=mapRound.questions[0],b=mapRound.questions[1],c=mapRound.questions[2],d=mapRound.questions[3],code=l=>l.feature.properties.adcode;
answer(mapRound,code(a));mark(a);await context.nextQuizQuestion();assert(states.get(code(a)).quizCorrect,'Correct answer lost after Next');
answer(mapRound,code(a));mark(b);mark(a,false);await context.nextQuizQuestion();
assert(states.get(code(a)).quizCorrect&&!states.get(code(a)).quizWrong,'An earlier correct answer lost its green state after a wrong click');
assert(!states.get(code(b)).quizCorrect,'Incorrect answer persisted as a successful answer');
answer(mapRound);mark(c);await context.nextQuizQuestion();assert(!states.get(code(c)).quizCorrect,'Revealed answer persisted');
answer(mapRound,code(d));mark(d);await context.nextQuizQuestion();assert(completed);assert(states.get(code(a)).quizCorrect&&states.get(code(d)).quizCorrect,'Results cleared solved regions');
mark(b);context.clearQuizHighlights(true);assert(!states.get(code(b)).quizCorrect&&states.get(code(a)).quizCorrect,'Missed-place review erased progress');
context.clearQuizHighlights();assert([...states.values()].every(s=>!s.quizCorrect&&!s.quizWrong),'Restart or exit retained quiz colors');assert.equal(quiz.highlighted.length,0);
console.log('Map quiz: correct regions stay green across Next, mistakes, reveals and results; restart/exit clears all highlights.');
